#!/usr/bin/env python3

HEADER = """
//! All (negative) integers which are at or near a power of two to test
//! boundary conditions. We use strings so we can convert to any type using
//! parsing, while still being able to use the *position* in ORDERED_VALS for
//! comparisons.
//!
//! DO NOT MODIFY: Generated by `src/etc/int_cast_vals.py`
"""


def generate_vals():
    pos_int_vals: set[int] = set()
    for exp in range(129):
        val = 1 << exp
        pos_int_vals.add(max(0, val - 2))
        pos_int_vals.add(max(0, val - 1))
        pos_int_vals.add(val)
        pos_int_vals.add(val + 1)
        pos_int_vals.add(val + 2)

    pos_str_vals = [str(v) for v in sorted(pos_int_vals)]

    out: list[str] = []
    for val in reversed(pos_str_vals[1:]):
        out.append(f"-{val}")
    out.extend(pos_str_vals)

    return out


def main():
    vals = generate_vals()
    print(HEADER.strip())
    print()
    print(f"pub(super) const N_ORDERED_VALS: usize = {len(vals)};")
    print()
    print("#[rustfmt::skip]")
    print("pub(super) static ORDERED_VALS: [&str; N_ORDERED_VALS] = [")
    for val in vals:
        print(f'    "{val}",')
    print("];")


if __name__ == "__main__":
    main()
