gcp_credentials: ENCRYPTED[5ee9e22237c8368fdae53b368a38509d62a168e1b5a8162a9bd8dfef5e874a4f41cd8235d498b99d2c2860c77e06ecd1]

gce_instance:
  image_project: ubuntu-os-cloud
  image_family: ubuntu-2404-lts-arm64
  architecture: arm64
  zone: us-east1-b
  type: c4a-standard-16
  disk: 60
  spot: true

env:
  # this needs to be known at parse time for the cache instruction
  HOST_TUPLE: "aarch64-unknown-linux-gnu"

_build_llvm: &BUILD_LLVM
  check_host_tuple_script: test -n "${HOST_TUPLE}"
  bootstrap_setup_script: CC="clang" CXX="clang++" ./x setup none
  llvm_cache:
    folder: build/$HOST_TUPLE/llvm
    fingerprint_script:
      - echo "4"
      - echo $HOST_TUPLE
      - git submodule status src/llvm-project
      - ./cheri/gen_bootstrap.py --build-clang -o -
    populate_script:
      - apt-get install -y cmake ninja-build
      - ./cheri/gen_bootstrap.py --build-clang -v
      - CC="clang" CXX="clang++" ./x build llvm
      - rm -r build/$HOST_TUPLE/llvm/build
      - rm bootstrap.toml
  gen_post_llvm_bootstrap_script:
    - ./cheri/gen_bootstrap.py --llvm-config-bin build/$HOST_TUPLE/llvm/bin/llvm-config -v

_build_sail_sim: &BUILD_SAIL_SIM
  sail_sim_cache:
    folder: cheriot-sail/c_emulator
    fingerprint_script:
      - git ls-remote https://github.com/CHERIoT-Platform/cheriot-sail refs/heads/main
    populate_script:
      - apt-get install -y libgmp-dev opam z3
      - git clone --recurse-submodules --depth=1 https://github.com/CHERIoT-Platform/cheriot-sail
      - opam init --reinit --bypass-check --disable-sandboxing --disable-shell-hook
      - eval $(opam env)
      - opam install sail --confirm-level=unsafe-yes
      - cd cheriot-sail && make csim
  install_sail_sim_script:
    - cp cheriot-sail/c_emulator/cheriot_sim /usr/local/bin

_common_setup: &COMMON_SETUP
  install_common_deps_script:
    - apt-get update
    - apt-get install -y ccache clang libssl-dev lld perl pkg-config
  setup_ccache_env_script:
    - echo "CCACHE_REMOTE_STORAGE=http://${CIRRUS_HTTP_CACHE_HOST}/${CIRRUS_OS}/" >> $CIRRUS_ENV
    - echo "CCACHE_REMOTE_ONLY=1" >> $CIRRUS_ENV

# populate_llvm_cache_task:
#   name: Populate LLVM cache
#   alias: populate_llvm_cache
#   timeout_in: 60m
#   env:
#     CIRRUS_CLONE_DEPTH: 1
#   <<: *COMMON_SETUP
#   <<: *BUILD_LLVM

x_check_task:
  # depends_on:
  #   - populate_llvm_cache
  name: Run `./x check` and `./x test tidy`
  alias: x_check
  timeout_in: 60m
  env:
    CIRRUS_CLONE_DEPTH: 1
  fetch_commit_history_script:
    # commit info is used by check/tidy, and we want to do this
    # before bootstrap inits submodules
    - git fetch --filter=tree:0 --unshallow origin HEAD
  <<: *COMMON_SETUP
  <<: *BUILD_LLVM
  check_env_script: env
  build_fmt_script: CC="clang" CXX="clang++" ./x build rustfmt
  rust_test_tidy_script: CC="clang" CXX="clang++" ./x test tidy
  rust_check_script: CC="clang" CXX="clang++" ./x check

x_test_task:
  only_if: false
  depends_on:
    - x_check
  name: Run `./x test`
  alias: x_test
  timeout_in: 60m
  env:
    CIRRUS_CLONE_DEPTH: 1
  <<: *COMMON_SETUP
  <<: *BUILD_LLVM
  check_env_script: env
  rust_test_script: CC="clang" CXX="clang++" ./x test --skip src/tools/linkchecker --skip tests/rustdoc-ui --skip tests/run-make --skip tidy

build_core_task:
  only_if: false
  depends_on:
    - x_check
  name: Build `core` library  for `riscv32cheriot-unknown-cheriotrtos`
  alias: build_core
  timeout_in: 60m
  env:
    CIRRUS_CLONE_DEPTH: 1
  <<: *COMMON_SETUP
  <<: *BUILD_LLVM
  check_env_script: env
  pull_main_script: git fetch origin main:refs/remotes/origin/main --depth 1
  build_script: CC="clang" CXX="clang++" ./x build compiler std --target=riscv32cheriot-unknown-cheriotrtos

run_cheri_tests_task:
  only_if: false
  depends_on:
    - x_check
  name: Run CHERIoT-specific tests
  alias: run_cheri_tests
  timeout_in: 60m
  env:
    CIRRUS_CLONE_DEPTH: 1
    CARGO_HOME: /tmp/cargo
    RUSTUP_HOME: /tmp/cargo
    XMAKE_ROOT: "y"
  <<: *COMMON_SETUP
  install_xmake_script:
    - curl -fsSL https://xmake.io/shget.text | bash || true # The installer will fail without any informations.
    - echo "PATH=/root/.local/bin:$PATH" >> $CIRRUS_ENV
  verify_xmake_script: xmake --version
  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
    - . "$CARGO_HOME/env" && echo "PATH=$PATH" >> $CIRRUS_ENV
  verify_rust_script: cargo --version
  <<: *BUILD_SAIL_SIM
  <<: *BUILD_LLVM
  check_env_script: env
  pull_main_script: git fetch origin main:refs/remotes/origin/main --depth 1
  build_rustc_script: CC="clang" CXX="clang++" ./x build compiler std --target=riscv32cheriot-unknown-cheriotrtos
  run_x_cheriot_tests_script: CC="clang" CXX="clang++" ./x test tests/codegen-llvm --target=riscv32cheriot-unknown-cheriotrtos --skip src/tools/linkchecker
  build_test_runner_script: cd ./cheri/tests/runner && cargo build --release
  run_tests_script:
    cd ./cheri/tests && ./runner/target/release/cheriot-runner -vvvvv .
    --sysroot=../../build/host/llvm
    --rustc=../../build/host/stage1/bin/rustc
  run_examples_script: cd ./cheri/examples && ./run_examples.sh

release_task:
  timeout_in: 120m
  depends_on:
    # EVERYTHING!
    - x_check
    - x_test
    - build_core
    - run_cheri_tests
  only_if: ($CIRRUS_PR == "") && ($CIRRUS_BRANCH == "beta")
  matrix:
    # Warning: the name of the tasks must mach the output of $(uname -p) in the runners.
    - name: Build and upload artefact x86_64
      gce_instance:
        image_project: ubuntu-os-cloud
        image_family: ubuntu-2404-lts-amd64
        architecture: amd64
        zone: us-east1-b
        type: t2d-standard-16
        disk: 60
        spot: true
    - name: Build and upload artefact aarch64
      gce_instance:
        image_project: ubuntu-os-cloud
        image_family: ubuntu-2404-lts-arm64
        architecture: arm64
        zone: us-east1-b
        type: c4a-standard-16
        disk: 60
        spot: true
  env:
    NINJA_STATUS: "%p [%f:%s/%t] %o/s, %es: "
    CIRRUS_CLONE_DEPTH: 1
  dependencies_script:
    - set -eo pipefail
    - apt-get update
    - apt-get install -y pkg-config clang ninja-build lld cmake ccache perl libssl-dev
  build_rustc_script:
    - |
      cat <<EOF > bootstrap.toml
      profile = "compiler"
      change-id = "ignore"

      [llvm]
      targets = "all"
      experimental-targets = ""
      download-ci-llvm = false
      build-config = {CMAKE_C_COMPILER="clang", CMAKE_CXX_COMPILER="clang++"}

      [build]
      ccache = true
      docs = false
      target = ["riscv32cheriot-unknown-cheriotrtos"]
      tools = ["cargo", "rustfmt"]

      [dist]
      compression-formats = ["gz"]

      [rust]
      channel = "dev"
      std-features = ["compiler-builtins-mem"]
      strip = true
      dist-src = false
      optimize = "z"
      EOF
    - ./x dist --target=riscv32cheriot-unknown-cheriotrtos
    - ./x dist cargo --target=riscv32cheriot-unknown-cheriotrtos
    - rm -r build/dist/rust-src* build/dist/rust-dev* build/dist/rustc-dev* build/dist/rustc-docs*
  binaries_artifacts:
    path: "build/dist/**"
