name: Autobump LLVM (CHERIoT)

on:
  schedule:
    # Create a PR to bump LLVM every Monday at 15:30.
    - cron: "30 15 * * 1"
      timezone: "Europe/London"
  # Needed so we can run it manually
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump_llvm:
    runs-on: ubuntu-slim
    timeout-minutes: 240
    steps:
      # Create a PK that will be used later to create the PR.
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.CHERI_PR_AUTOMATOR_APP_ID }}
          private-key: ${{ secrets.CHERI_PR_AUTOMATOR_APP_PK }}
      - name: Does GH CLI work?
        run: gh auth status
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Install credentials
        run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      - uses: actions/checkout@v5
        name: Checkout
        with:
          fetch-depth: 2
      - name: Pull changes from LLVM
        run: |
          echo $(pwd)
          git submodule sync
          git submodule update --init --depth=1 src/llvm-project
          cd src/llvm-project
          echo "CURRENT_LLVM_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          git fetch
          echo "NEXT_LLVM_COMMIT=$(git rev-parse --short origin/HEAD)" >> $GITHUB_ENV
          git checkout $(git rev-parse --short origin/HEAD)

      - name: Create commit
        if: env.CURRENT_LLVM_COMMIT != env.NEXT_LLVM_COMMIT
        run: |
          git config --global user.name "cheri-pr-automator[bot]"
          git config --global user.email "288880664+cheri-pr-automator[bot]@users.noreply.github.com"
          git add src/llvm-project && git commit -m "Bump LLVM to $NEXT_LLVM_COMMIT"
          echo "BRANCH_NAME=autobump-llvm-$NEXT_LLVM_COMMIT-$(date +"%d-%m-%y")" >> $GITHUB_ENV

      - name: Switch branch
        if: env.CURRENT_LLVM_COMMIT != env.NEXT_LLVM_COMMIT
        run: |
          git switch -c ${{ env.BRANCH_NAME }}

      - name: Push to branch
        if: env.CURRENT_LLVM_COMMIT != env.NEXT_LLVM_COMMIT
        run: |
          git config --global push.autoSetupRemote true
          git push

      - name: Create PR
        if: env.CURRENT_LLVM_COMMIT != env.NEXT_LLVM_COMMIT
        run: gh pr create -base="beta" --title="[Weekly Autobump] Bump LLVM to $NEXT_LLVM_COMMIT" --body="Good luck!"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
