name: CI (CHERIoT)

on:
  push:
    branches:
      - "beta"
      - "main"
  pull_request:
    branches:
      - "**"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: warp-custom-gcp-aarch64-32cpu
    timeout-minutes: 240
    env:
      CC: "clang"
      CXX: "clang++"
    steps:
      - name: Install dependencies
        run: |
          set -eo pipefail
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo apt update
          sudo apt install -y xmake pkg-config clang ninja-build lld cmake perl opam z3 libgmp-dev libssl-dev git zlib1g-dev

        # after apt install git
      - uses: actions/checkout@v5
        name: Checkout
        with:
          # Don't pull any commits if we are targeting 'main', because that may break CI.
          fetch-depth: ${{ case( github.ref_name == 'main', 0, 2 ) }}

      - name: Checkout submodules
        run: ./src/ci/scripts/checkout-submodules.sh

        # seperate bootstrap setup logs from later tasks
      - name: Initialise bootstrap
        run: ./x setup none --ci=false

      - name: Install sccache
        env:
          # we keep to daemon alive so we can check the stats at the end
          SCCACHE_IDLE_TIMEOUT: 14400
          # version used upstream
          URL: https://ci-mirrors.rust-lang.org/rustc/2025-02-24-sccache-v0.10.0-aarch64-unknown-linux-musl
        run: |
          curl -fo /usr/local/bin/sccache "$URL"
          chmod +x /usr/local/bin/sccache
          sccache --start-server

      - name: Restore sccache cache
        id: restore-sccache
        uses: WarpBuilds/cache/restore@v1
        with:
          path: ~/.cache/sccache
          # this should be empty
          key: sccache-${{ runner.arch }}-${{github.ref}}-${{github.run_id}}
          # but we might have one of these:
          restore-keys: |
            sccache-${{ runner.arch }}-${{github.ref}}
            sccache-${{ runner.arch }}

      - name: Clear sccache stats
        run: sccache --zero-stats

      - name: Configure bootstrap
        run: ./configure --set profile=cheriot --enable-sccache --disable-manage-submodules

      - name: Run `x test tidy` (host)
        run: ./x test tidy --ci=false

      - name: Build LLVM
        run: ./x build llvm --ci=false

      - name: Run `x check` (host)
        run: ./x check --ci=false

      - name: Run `x test` (host)
        run: ./x test --skip src/tools/linkchecker --skip tests/rustdoc-ui --skip tests/run-make --skip tidy --ci=false

      - name: Build rustc, core (CHERIoT)
        run: ./x build compiler std --target=riscv32cheriot-unknown-cheriotrtos --ci=false

      - name: Run `x test tests/codegen-llvm` (CHERIoT)
        run: ./x test tests/codegen-llvm --target=riscv32cheriot-unknown-cheriotrtos --skip src/tools/linkchecker --ci=false

      - name: Check xmake
        run: xmake --version

      - name: Install Rust (upstream stable)
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
          . "$HOME/.cargo/env" && echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Check rust
        run: cargo --version

      - name: Install Sail
        run: |
          wget https://github.com/rems-project/sail/releases/download/0.20.1/sail-Linux-aarch64.tar.gz
          tar xfv sail-Linux-aarch64.tar.gz
          echo "PATH=$PATH:$(pwd)/sail/bin" >> $GITHUB_ENV

      - name: Build Sail simulator
        run: |
          git clone --recurse-submodules --depth=1 https://github.com/CHERIoT-Platform/cheriot-sail
          opam init --reinit --bypass-check --disable-sandboxing --disable-shell-hook
          eval $(opam env)
          cd cheriot-sail && make csim -j$(nproc) && sudo cp c_emulator/cheriot_sim /usr/local/bin
        env:
          CC: "cc"
          CXX: "cpp"

      - name: Check sail sim
        run: cheriot_sim

      - name: Build test runner (host)
        working-directory: ./cheri/tests/runner
        run: cargo build --release

      - name: Run internal tests (CHERIoT)
        working-directory: ./cheri/tests
        run: ./runner/target/release/cheriot-runner -vvvvv . --sysroot=../../build/host/llvm --rustc=../../build/host/stage1/bin/rustc

      - name: Run examples (CHERIoT)
        working-directory: ./cheri/examples
        run: ./run_examples.sh

      - name: Build rustc, std (CHERIoT/facade)
        run: ./x build compiler std --target=riscv32cheriot-unknown-cheriotrtos.facade --ci=false

      - name: Build test-runner
        run: cargo install --path cheri/ci/tools/test_runner

      - name: Run coretests (CHERIoT/facade)
        run: test-runner coretests --known-issues library/coretests/known_issues

      - name: Check sccache stats
        if: always()
        run: sccache --show-stats

      - name: Save sccache cache
        if: always()
        id: sccache-save
        uses: WarpBuilds/cache/save@v1
        with:
          path: ~/.cache/sccache
          key: sccache-${{ runner.arch }}-${{github.ref}}-${{github.run_id}}

      - name: Check disk
        if: always()
        run: df -h

      - name: Check env
        if: always()
        run: env
